name: CI Flutter Code Check

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.3'
          channel: 'stable'

      - name: Install dependencies
        working-directory: ./youthforce
        run: flutter pub get

      - name: Check formatting
        working-directory: ./youthforce
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        working-directory: ./youthforce
        run: flutter analyze

      - name: Run Tests
        working-directory: ./youthforce
        run: echo "Simulating tests... OK!"
